name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 49.51.69.152
          username: root
          # Kita akan setting secret ini di GitHub sebentar lagi
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/gunggg-airdrop/htdocs/airdrop.gunggg.online
            git pull origin main
            # Hapus folder dist lama jika ada
            rm -rf dist
            # Jalankan build (pastikan Node.js sudah terinstall di VPS)
            npm install
            npm run build
            # Pindahkan hasil build ke folder htdocs utama
            cp -r dist/* .