name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 49.51.69.152
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Tambahkan ini agar tidak ditolak GitHub karena fingerprint
          fingerprint: ${{ secrets.SSH_FINGERPRINT }} 
          # ATAU tambahkan baris ini jika tidak ingin ribet dengan fingerprint (kurang aman tapi manjur):
          # debug: true
          script: |
            cd /home/gunggg-airdrop/htdocs/airdrop.gunggg.online
            git fetch --all
            git reset --hard origin/main
            
            # Gunakan --legacy-peer-deps untuk mengabaikan bentrok versi Tailwind/Vite
            npm install --legacy-peer-deps
            
            # Jalankan build
            npm run build
            
            # Hapus file index.html lama bawaan CloudPanel jika masih ada
            rm -f index.html
            
            # Pindahkan hasil build
            cp -r dist/* .